name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Version
      run: |
          export VERSION="${GITHUB_RUN_NUMBER}.${GITHUB_SHA:0:7}"
          echo $VERSION
          env
