name: Deploy from PR comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-comments:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to trigger a workflow dispatch
    if: ${{ github.event.comment.body == 'deploy' }}
    steps:
      - name: Github event details
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context))
      - name: env
        run: env | sort
      - name: Trigger release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +x
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/release.yml/dispatches \
            -d '{"ref":"refs/pull/${{ github.event.issue.number }}/merge"}'
