name: Deploy from PR comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-comments:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'deploy' }}
    steps:
      - name: Github ref
        run: echo GITHUB_REF=${GITHUB_REF}
