name: Deploy from PR comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-comments:
    runs-on: ubuntu-latest
    permissions:
      actions: write # to trigger a workflow dispatch
    if: ${{ github.event.comment.body == 'deploy' }}
    steps:
      - name: Github event details
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context))
      - name: env
        run: env | sort
      - name: Trigger release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: 'main',
            })
