name: release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Github event details
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context))
